name: upload-source
on: 
  push:
    branches:
      - main
jobs:
  upload_source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'source.zip'

      - name: S3 Sync
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp source.zip s3://${{ secrets.AWS_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
