name: Upload Source to S3

on:
  push:
    branches: alternate*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: S3 Sync
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync . s3://${{ secrets.AWS_BUCKET }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: "ap-southeast-2"
